### ISSUE TITLE
Looses orientation when presenting a modal view controller

### ISSUE THREAD

**Issue by pier-oliviert** [mattgemmell/MGSplitViewController#11]
When you present a modal view controller, if you change orientation while in the modal, the whole MGSplitViewController loose it's orientation

**Comment by pier-oliviert** [comment]
Nevermind, I had a problem here. :(

**Comment by mattgemmell** [comment]
Glad you got it fixed!

**Comment by pier-oliviert** [comment]
Actually I got confused with the methods and some boolean,

if showMasterInLandscape is set to NO, if you use
- (IBAction)toggleMasterView:(id)sender, shouldn't it be ignore if showMasterInLandscape is set to NO ? I would have assumed that showMasterInLandscape has a higher priority than sending explicit action?

Also, I had was about to create my own splitViewController myself, so it was a relief that you did all the extra work.

**Comment by mattgemmell** [comment]
toggleMasterView: actually changes the relevant "showMasterIn..." setting; it's designed that way.
