### ISSUE TITLE
When changing orientation while in a modal viewcontroller, the orientation loses itself when dismissing the modal

### ISSUE THREAD

**Issue by pier-oliviert** [mattgemmell/MGSplitViewController#13]
Step to reproduce:
1. Launch a modal View controller
2. Rotate
3. Dismiss the modal

I'm currently working on fixing the issue but I'm not clear what is causing it

**Comment by daikini** [comment]
Are you presenting the modal view controller from the split view controller?

[splitController presentModalViewController:someViewController animated:YES];

If not, that could be the issue.

**Comment by pier-oliviert** [comment]
Surprisingly it fixed the issue, but it should be mention somewhere as this is clearly something dev should be aware of.
