### ISSUE TITLE
_viewControllers may contain NSNull, setViewControllers: doesn't expect that

### ISSUE THREAD

**Issue by Jeffrey903** [mattgemmell/MGSplitViewController#3]
setViewControllers: iterates over _viewControllers and assumes that each item is a UIViewController (and accesses the view property).  However, it is possible for an item in _viewControllers to be [NSNull null], so there needs to be a check for

if ([controller isKindOfClass:[UIViewController class]])

inside the for loop.

**Comment by mattgemmell** [comment]
Good catch; fixed and pushed.
