### ISSUE TITLE
setDetailViewController() does not reload view?

### ISSUE THREAD

**Issue by hautelook-jimmy** [mattgemmell/MGSplitViewController#37]
i'm trying to change the detail view with setDetailViewController() method, but nothing was working. 

I play around with different options, i was able to use setViewControllers() to reload both master and detail views.

After i study the code a little more, i found out that in setViewControllers(), it remove all the views from the superview, before doing anything else.

```
    for (UIViewController *controller in _viewControllers) {
        if ([controller isKindOfClass:[UIViewController class]]) {
            [controller.view removeFromSuperview];
        }
    }
```

So, i added the same code in the setDetailViewController(), and it seem to work perfectly.

```
    if ([_viewControllers objectAtIndex:1] == detail) {
        changed = NO;
    } else {
        if ([[_viewControllers objectAtIndex:1] isKindOfClass:[UIViewController class]]) {
            [[[_viewControllers objectAtIndex:1] view] removeFromSuperview];
        }
        [_viewControllers replaceObjectAtIndex:1 withObject:detail];
    }
```

Is this a bug in the code? or is there an easier way to replace the detail view without touching the master view?

**Comment by jonsterling** [comment]
Yeah, I'm also having this problem.

**Comment by ashrafulkarim** [comment]
I had the same problem. But this technique  help me to resolve the issue. thanks.

**Comment by Inza** [comment]
Excelent hautelook-jimmy! Thanks you very much! I really own you one for that;). Will it be fixed in the repo by the author, or should I create a pull request for it?

**Comment by hautelook-jimmy** [comment]
I haven't seen author updating the code for a long time.  so i basically just subclass it and override the entire method.
