### ISSUE TITLE
Crash when calling setViewControllers:

### ISSUE THREAD

**Issue by akosma** [mattgemmell/MGSplitViewController#5]
In a fairly complex app using UISplitViewController I replaced it with MGSplitViewController and had a crash on startup; I could solve the crash by applying this change to the class:
http://gist.github.com/503462
(I must say that the class worked perfectly well just by changing the class names from UI to MG. _Amazing_ work.)

**Comment by mattgemmell** [comment]
Already fixed earlier today!
