### ISSUE TITLE
setViewControllers bug

### ISSUE THREAD

**Issue by liamlynass** [mattgemmell/MGSplitViewController#6]
setViewControllers should check for controller!=[NSNull null] before removing from the views parent. The following code should work as a replacement.
- (void)setViewControllers:(NSArray *)controllers
  {
  if (controllers != _viewControllers) {
      for (UIViewController *controller in _viewControllers) {
          if((NSNull *)controller != [NSNull null]){
              [controller.view removeFromSuperview];
          }
      }
      [_viewControllers release];
      _viewControllers = [[NSMutableArray alloc] initWithCapacity:2];
      if (controllers && [controllers count] >= 2) {
          self.masterViewController = [controllers objectAtIndex:0];
          self.detailViewController = [controllers objectAtIndex:1];
      } else {
          NSLog(@"Error: %@ requires 2 view-controllers. (%@)", NSStringFromClass([self class]), NSStringFromSelector(_cmd));
      }
  
  ```
  [self layoutSubviews];
  ```
  
  }
  }

**Comment by liamlynass** [comment]
Whoops - just noticed this is a dup!

**Comment by mattgemmell** [comment]
Fixed earlier today. :)
