### ISSUE TITLE
Framework and sample project is mixed

### ISSUE THREAD

**Issue by chbeer** [mattgemmell/MGSplitViewController#8]
I like you implementation as it is very useful and something I was about to build myself. But I find it a bit complicated, that one needs to get the relevant classes out of the sample project. A better solution would be to create your MGSVC framework as a static lib that can be included in some easy steps. Your sample project could include this project aswell.
Three20 did a great job splitting the framework from the sample project those days.

Just my 2ct.

**Comment by mattgemmell** [comment]
Will certainly take that under consideration.

**Comment by chbeer** [comment]
That would also improve the updateability for those who use your classes.

**Comment by mattgemmell** [comment]
What I tend to do is have one checkout of the project on my disk, and then include the relevant files in as many other projects as I want (without copying them into each project folder). That way they all get updated at once, and there's no duplication.
