### ISSUE TITLE
How to push MGSplitview controller to a Navigation controller ?

### ISSUE THREAD

**Issue by ibiren** [mattgemmell/MGSplitViewController#83]
I am facing issue while trying to push MGSplitview onto a Navigation controller.. Pls help!

**Comment by sebastianwr** [comment]
Since you don't provide any useful debugging information or effort on your side:

```
[[self navigationController] pushViewController:[[MySubclassOfMGSplitViewController alloc] init] animated:YES];
```

works perfectly fine here.
