### ISSUE TITLE
iOS 7 Adapting Size for master and detail

### ISSUE THREAD

**Issue by phynet** [mattgemmell/MGSplitViewController#88]
I was having a problem with  both views sizes (master and detail) in iOS 7, calculating the height of the view substracting the size of the status bar isn't the right way anymore, I've added in method:
- (CGSize)splitViewSizeForOrientation:(UIInterfaceOrientation)theOrientation

This line:

```
if([[[UIDevice currentDevice] systemVersion] intValue] < 7)
    height -= statusBarHeight;
```

It's working, although I believe there's got to be a better way. ¿?

**Comment by bestimmaa** [comment]
Thanks for pointing out the right position in the code, I experienced the same issue and just wanted to search for this. I think it safe to assume that the status bar overlaps the view controller because there is no other behavior available in iOS7.

**Comment by fechu** [comment]
Check out this version of the fix. It looks a little bit less hacked. :-D

https://github.com/kurtzmarc/MGSplitViewController/commit/94b33c750300a0f0b0f846a941f470e4c8fa98c6
