### ISSUE TITLE
initWithFrame: not supported

### ISSUE THREAD

**Issue by chbeer** [mattgemmell/MGSplitViewController#9]
The MGSplitViewController class only contains the constructors initWithNibName:bundle: and initWithCoder: but no initWithFrame: constructor. 

As I am trying to create the MGSVC from code I get some problems because setup does not get called in that case.

**Comment by chbeer** [comment]
Well... OK. I should first check the documentation before posting issues. Sorry for that.

The thing is: there is no initWithFrame: for a IUViewController. But a plain init should be supported IMHO.

**Comment by mattgemmell** [comment]
Wouldn't setup be called twice in that case, since init will be called from the superclasses' designated initialisers, eventually? Better to just use the initWithNibName:bundle: initialiser will nil arguments.
