### ISSUE TITLE
Broken by iOS8 

### ISSUE THREAD

**Issue by ConfusedVorlon** [mattgemmell/MGSplitViewController#95]
in iOS8, the master controller is 'popped' out of the drawer, and displayed as a popover.

(this only happens for me the second and subsequent time I show the drawer)

I hope you can re-visit this, it's a great bit of code!

**Comment by ConfusedVorlon** [comment]
this is the demo app after clicking 'show master'

![2014-06-06 08 07 24 pm](https://cloud.githubusercontent.com/assets/586910/3204785/d34c0d16-edad-11e3-9990-5d481535d756.png)

**Comment by ConfusedVorlon** [comment]
update for anyone interested: Matt has told me that he isn't developing this any more, so there won't be a fix from him.

**Comment by MyIDABC** [comment]
@ConfusedVorlon  Do you have an updated version of MGSplitViewController for iOS8?

**Comment by ConfusedVorlon** [comment]
@MyIDABC the last iOS beta fixed my issue.
